# exampleSite/config.yaml
baseURL: https://swleeeeee.github.io/Crafeeee/ # Replace with your domain
languageCode: en-us
theme: smigle
themesDir: themes # Only needed for running the example site
title: Crafeeee's 
menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4



params:
  abbrDateFmt: "Jan 2"
  author: "Crafeeee"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"

  social:
    - name: GitHub
      url: https://github.com/
    - name: Bilibili
      url: https://space.bilibili.com/115155048
    - name: CSDN
      url: https://blog.csdn.net/m0_59162304?spm=1000.2115.3001.5343
  subtitle: "Gains can't stop"
